/**
 * SeekerAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Job {
    'id'?: number;
    'preview'?: string | null;
    'content'?: string | null;
    'postedDate'?: Date;
    'filter'?: JobFilterEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "preview",
            "baseName": "preview",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "postedDate",
            "baseName": "postedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "JobFilterEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Job.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum JobFilterEnum {
    None = 'None',
    Important = 'Important',
    AutoIgnore = 'AutoIgnore',
    Hidden = 'Hidden',
    Applied = 'Applied'
}

