/**
 * SeekerAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JobFilter {
    'id'?: number;
    'text'?: string | null;
    'type'?: JobFilterTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "JobFilterTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JobFilter.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum JobFilterTypeEnum {
    None = 'None',
    Important = 'Important',
    AutoIgnore = 'AutoIgnore',
    Hidden = 'Hidden',
    Applied = 'Applied'
}

