/**
 * SeekerAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ServiceState {
    'jobsCount'?: number;
    'retrieveInProgress'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobsCount",
            "baseName": "jobsCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "retrieveInProgress",
            "baseName": "retrieveInProgress",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ServiceState.attributeTypeMap;
    }

    public constructor() {
    }
}

