/**
 * SeekerAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SyncState {
    'inProgress'?: boolean;
    'currentRequest'?: string | null;
    'progressPercentage'?: number;
    'currentPage'?: number;
    'currentPagePercentage'?: number;
    'startedAt'?: Date;
    'uniqJobsCount'?: number;
    'importantCount'?: number;
    'autoIgnoredCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inProgress",
            "baseName": "inProgress",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentRequest",
            "baseName": "currentRequest",
            "type": "string",
            "format": ""
        },
        {
            "name": "progressPercentage",
            "baseName": "progressPercentage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "currentPage",
            "baseName": "currentPage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "currentPagePercentage",
            "baseName": "currentPagePercentage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "uniqJobsCount",
            "baseName": "uniqJobsCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "importantCount",
            "baseName": "importantCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "autoIgnoredCount",
            "baseName": "autoIgnoredCount",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return SyncState.attributeTypeMap;
    }

    public constructor() {
    }
}

